### ISSUE TITLE
image processor is None

### ISSUE THREAD

**Issue by limaopeng1** [LingyvKong/OneChart#10]
The following error message appears when running vary/train/train_opt.py：

Traceback (most recent call last):
  File "/workspace/OneChart/OneChart_code/vary/data/conversation_dataset_v1_with_number.py", line 183, in __getitem__
    image, image_1 = self.image_processor(image)
  File "/workspace/OneChart/OneChart_code/vary/data/base_dataset.py", line 56, in image_processor
    image = processor.preprocess(image, return_tensors='pt')['pixel_values'][0]
AttributeError: 'NoneType' object has no attribute 'preprocess'

In  vary_opt_math.py:
         # 224*224
        image_processor = None # CLIPImageProcessor.from_pretrained() 
        # 1024*1024
        image_processor_high = test_transform 

How should I modify this?

**Comment by Ucas-HaoranWei** [comment]
If you want to train the model, simply handle it as follows and the bug will be fixed soon:
 
![image](https://github.com/LingyvKong/OneChart/assets/50487563/271808c3-b1d6-4503-9d3a-99605eec8a5f)

**Comment by LingyvKong** [comment]
fixed in this [commit](https://github.com/LingyvKong/OneChart/commit/1099125d41ce4f7a9f30538bbf85a482159d958a)
