### ISSUE TITLE
varyOPTForCausalLM.forwad 函数没有传递loc_labels参数

### ISSUE THREAD

**Issue by limaopeng1** [LingyvKong/OneChart#12]
varyOPTForCausalLM.forwad 函数没有传递loc_labels，导致numbers分支没有训练，应该在哪里修改？

![image](https://github.com/LingyvKong/OneChart/assets/32221220/2de47e68-f5f8-43b7-a407-333980fd82e4)

**Comment by LingyvKong** [comment]
fixed in latest commit
