### ISSUE TITLE
推理速度慢

### ISSUE THREAD

**Issue by hkxxxxx** [LingyvKong/OneChart#14]
我在一张A5000上进行了部署，对模型进行了推理测试，结果十分优秀，但是唯一的问题在于推理速度慢，有些便于解析的chart推理时长在20s内，有些复杂的chart需要更久的时间，比如70s之久。想问下有没有可以加快推理速度的方法？在run_opt_v2.py中我们对每一部分进行了计时，发现model.generate需要的时间占了绝大部分，请问这是由于Qwen推理速度慢的原因吗？有没有相应的解决方法？
![image](https://github.com/LingyvKong/OneChart/assets/77883069/89dee46d-f659-4e33-b60f-ae1e7a62a6ae)

**Comment by LingyvKong** [comment]
It seems that your CUDA is not installed correctly, and the model may be inferring on the CPU. The inference speed should be very fast. You can refer to the speed of the [web demo](https://onechartt.github.io/), which is only deployed on a 1080Ti and has a considerable network delay.
