### ISSUE TITLE
Wrong generation contents after fine-tuning 

### ISSUE THREAD

**Issue by edsml-js222** [LingyvKong/OneChart#16]
Hi, firstly thanks for the great work! 
But I just encountered an issue when I tried to fine-tune the model with my chart data. My training data has 6k charts in various types such as 3D bar chart,  box, heatmap, etc. The annotation format is showed as the 1st image below. However, the results generated by the model seems to become chaos since neither of its content or format stick to the right (2nd image is the result from downloaded one-chart weight, 3rd is the one resulted after the fine-tune I mentioned). What might cause the problem? Could you please give me some insights? Really appreciate!
<img width="984" alt="截屏2024-06-11 17 44 21" src="https://github.com/LingyvKong/OneChart/assets/110098381/5c5fe6ed-15fd-4422-9854-a150f739d317">
<img width="238" alt="截屏2024-06-12 12 05 07" src="https://github.com/LingyvKong/OneChart/assets/110098381/557289a2-ea98-49ea-aee1-86a4724e4817">
<img width="644" alt="截屏2024-06-12 12 05 31" src="https://github.com/LingyvKong/OneChart/assets/110098381/4f9dcf5f-d566-4d02-9b86-9e9627ee1cad">

**Comment by edsml-js222** [comment]
sorry for the mis-uploaded image order. Now the 1st image is the wrong generated content, 3rd is the annotation.

**Comment by Ucas-HaoranWei** [comment]
It is because you do not input the image to the model during your training.
The "human-value" in "conversations" should be "<image>\nGenerate a descriptive xxxxx". The "<image>" token is necessary.
