### ISSUE TITLE
微调时报错：IndexError: index 0 is out of bounds for dimension 0 with size 0

### ISSUE THREAD

**Issue by yazheng0307** [LingyvKong/OneChart#25]
报错位置：  

File "/root/OneChart/OneChart_code/vary/model/vary_opt_math.py", line 272, in forward
    det_patch_token = torch.where(input_ids == self.config.number_token)[1][0]
IndexError: index 0 is out of bounds for dimension 0 with size 0

训练集格式：
![image](https://github.com/user-attachments/assets/2f52dd6c-95da-451d-8ffc-91701e20f410)

**Comment by LingyvKong** [comment]
我更新了readme中的train部分，修改json格式后再试试

**Comment by Garry101CN** [comment]
It looks like the "<Chart>" token was not implemented in author's provided dataset preparation. However, the decoder tried to locate the token through its id, which leads to a result of 0 in torch.where when it was going to calculate num loss.

Adding "<Chart>"(or "<Number>" in author's code) to the assistant part of the conversation will bring you on your way.

**Comment by yazheng0307** [comment]
> 我更新了readme中的train部分，修改json格式后再试试

我看您更新了数据集的格式，有两个问题请教一下：
1、Readme里面说，If the auxiliary head is Not used and trained, the format example is xxx，请问如果我想按照示例1的数据格式进行训练，auxiliary head开关在哪控制？

2、示例2中的 "Numbers": [6.12, 5.32, 5.11, 4.5, 1.45]，这类数据内容是必须要写的吗？只把value的数据加上前缀<Number>是否可行？

**Comment by LingyvKong** [comment]
1. 关掉auxiliary head，我没有写开关，你可以通过注释 [这行代码](https://github.com/LingyvKong/OneChart/blob/868942ace688231ba74e7ab3f1fe028d6c4776c6/OneChart_code/vary/data/conversation_dataset_v1_with_number.py#L214) 实现这个目的
2. 如果你不要auxiliary head，可以不写"Numbers": [6.12, 5.32, 5.11, 4.5, 1.45]
