### ISSUE TITLE
微调时numbers_loss始终为nan

### ISSUE THREAD

**Issue by yazheng0307** [LingyvKong/OneChart#26]
按照作者新提供的训练格式，微调过程中numbers_loss始终为nan，不知道什么原因？

训练格式：
![image](https://github.com/user-attachments/assets/9dabf083-bff5-4515-be12-35e8b80c9261)

微调日志：
![image](https://github.com/user-attachments/assets/fc10e8e2-519d-4064-8167-fe4a59373b72)

微调脚本：
`export PYTHONPATH=$PYTHONPATH:/root/OneChart/OneChart_code
deepspeed vary/train/train_opt.py \
    --deepspeed zero_config/zero2.json \
    --model_name_or_path /root/OneChart/weights/OneChart/ \
    --vision_tower /root/OneChart/weights/OneChart/ \
    --freeze_vision_tower False \
    --freeze_lm_model False \
    --vision_select_layer -2 \
    --use_im_start_end True \
    --bf16 True \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 250 \
    --save_total_limit 1 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --report_to none \
    --per_device_train_batch_size 2 \
    --num_train_epochs 1 \
    --learning_rate 5e-5 \
    --datasets chart_understand \
    --output_dir checkpoints/onechart-finetune/`

**Comment by LingyvKong** [comment]
啊抱歉，"Numbers"应该在data["conversations"]的"gpt"里面，我已经更正了readme

**Comment by yazheng0307** [comment]
好的，终于正常训练了，谢谢回复 (*^▽^*)
