### ISSUE TITLE
无法复现opt的OCR效果

### ISSUE THREAD

**Issue by luohao123** [LingyvKong/OneChart#3]
尝试更换chart数据到普通的文档ocr数据，训练loss无法收敛。

**Comment by LingyvKong** [comment]
There is temporarily available solution to this issue: [Refer to this](https://github.com/Ucas-HaoranWei/Vary-toy/issues/30#issuecomment -2050877639)

**Comment by Ucas-HaoranWei** [comment]
为什么用chart模型训练ocr数据？

**Comment by Ucas-HaoranWei** [comment]
This problem will be addressed [here](https://github.com/Ucas-HaoranWei/Vary-tiny)
