### ISSUE TITLE
About train set.

### ISSUE THREAD

**Issue by XuZhengzhuo** [LingyvKong/OneChart#5]
Hi,

Table 1 shows a large number of GPT-based charts. 
Is CSV data reused among them? 
Will all CSV data be open soon?

Thanks for your contributions!

**Comment by Chienjy** [comment]
1. No reused. Each image only has a unique JSON corresponding to it.
2. The files generated by GPT-3.5 are in Jsonl format. If you need them, you can leave your email.

**Comment by XuZhengzhuo** [comment]
Many THANKs and here is my gmail xzzthu@gmail.com

**Comment by limaopeng1** [comment]
@XuZhengzhuo 
I also want this file generated by GPT3, thank you very much.
Here is my email 847723615@qq.com

**Comment by XuZhengzhuo** [comment]
抱歉，这批数据不属于我，请向论文作者请求使用这批数据。
祝好～




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LingyvKong/OneChart"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月25日(星期四) 下午5:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LingyvKong/OneChart] About train set. (Issue #5)





 
@XuZhengzhuo
 I also want this file generated by GPT3, thank you very much.
 Here is my email ***@***.***

**Comment by yazheng0307** [comment]
你好，我也需要这个数据，这是我的邮箱：981638732@qq.com，感谢作者团队 @Chienjy

**Comment by yeolwoo0803** [comment]
@XuZhengzhuo 
I also want this file generated by GPT3.5, thank you very much.
Here is my email tjddufdn@gmail.com

**Comment by samaritan1998** [comment]
你好，可以也给我发送一份么，这是我的邮箱：aryazheng@163.com，感谢作者团队 @Chienjy

**Comment by xiapengchng** [comment]
你好，可以也给我发送一份吗， 849524134@qq.com ，感谢作者团队 @Chienjy

**Comment by whut2962575697** [comment]
你好，可以也给我发送一份吗， [2962575697@qq.com](mailto:2962575697@qq.com) ，感谢作者团队 @Chienjy

**Comment by iMountTai** [comment]
你好，我也想要这个数据，这是我的邮箱：[yaoxin@cumt.edu.cn](yaoxin@cumt.edu.cn)，感谢作者团队 @Chienjy

**Comment by ll0o0ll** [comment]
你好作者，能提供一下训练数据嘛，这是我的邮箱：zhaohs0412@163.com,感谢作者团队 @Chienjy
