### ISSUE TITLE
Magnitude of Training Dataset

### ISSUE THREAD

**Issue by zhang-jr** [LingyvKong/OneChart#9]
Hello, thank you for sharing your solid work.

I have a few questions about the size of the training dataset:
1. The paper mentions that the process in Figure 2 generated about 10M images;
2. The data you used for fine-tuning in Table 1 is about 2.7M. 

However, based on the data you [provided](https://drive.google.com/drive/folders/1YmOvxq0DfOA9YKoyCZDjpnTIkPNoyegQ), I counted only about 43K. Is there any discrepancy?

**Comment by zhang-jr** [comment]
Thank you for your clarification. Any plans to release the whole training data?

**Comment by Chienjy** [comment]
Sorry, we currently do not have this plan. You may be able to prepare your own training data based on the data engine mentioned in the paper.
